server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/banking_core_service
    username: root
    password: youssef1515
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true

  zipkin:
    enabled: false

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

eureka:
  client:
    enabled: false
