version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: youssef1515
      MYSQL_DATABASE: banking_core_service

    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      mysql-net:
        ipv4_address: 172.25.0.9
  core-banking-service:
    build: ../core-banking-service
    container_name: core-banking-service
    ports:
      - "8092:8092"
    depends_on:
      - mysql
    networks:
      mysql-net:
        ipv4_address: 172.25.0.2

volumes:
  mysqldata:

networks:
  mysql-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
